### ISSUE TITLE
SVG Icons - Not that easy to implement the svg sprite files in the CMS

### ISSUE THREAD

**Issue by jminguely** [frontend/toolbox-reader#19] opened 2017-08-17 13:55 UTC
It could be nice to be able to add some markup before or after the rendered styleguide.

For example, with my issue with the svg sprite, I could add

```
{{ source('build/icons/icons.svg') }}
```

just after the `<body>` tag & it will be the same for the CMS implementation

**Comment by tonifisler** [comment] 2017-08-23 06:02
I think this is a duplicate of #7

**Closed as completed by tonifisler** 2017-08-23 06:02 UTC
